### ISSUE TITLE
IE8 wont corner over CSS background

### ISSUE THREAD

**Issue by Tweakin** [malsup/corner#26]
I am using corner to round out the corners of a container on a fixed-width centered layout. The body has a CSS background image (jpg) that is repeated. I apply a corner to the container and all is well except in IE8, it will not corner unless I remove the background image of the body via CSS- if I do that, it corners just fine.

Is this a limitation or is there a work around?

**Comment by malsup** [comment]
Demo page?

**Comment by nathanielks** [comment]
I'm having the same issue in both IE8 and 7: http://ftcmedia.com/corner_bug/index.html

**Comment by malsup** [comment]
That's a limitation of the plugin.  If you look closely you'll see that it is applying a corner in IE, only the corner is white because that is the bg color of your page (note that your background-color style is wiped out on the very next line of your css).  You may get good-enough results by changing your body style to:

background: #891918 url(images/bg.jpg);

This plugin uses solid colors for the corners.
